version: '3.7'

services:
  postgres:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 54321:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - postgres
    container_name: 'hackerank-backend-test'
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - PGHOST=postgres
      - PGPORT=5432
    volumes:
      - ./:/app
